# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c916fbd1c8a16458c3495d8bd5e2a37aabeaa349d4ded201b7cf48b0119493af1f56ecf7a664b871d562913b4afb1c5956b8af0d861a74e25456d7f2b1a5e2c1

test:
  secret_key_base: eaa5f842d3c0bbfe211c8a1827914368f12f7e022965854c878d12dce925969dc01ff57c992535f9d2c1015a1dcbecea8ee2fb583d34bf057e1b5e26e9f1c652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
